FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

COPY ["src/Api/Api.csproj", "src/Api/"]
COPY ["src/Domain/Domain.csproj", "src/Domain/"]
COPY ["src/Common/Common.csproj", "src/Common/"]
COPY ["src/Infrastructure/Infrastructure.csproj", "src/Infrastructure/"]
COPY ["src/Application/Application.csproj", "src/Application/"]

WORKDIR /app/src/Api
RUN dotnet restore "Api.csproj"
     
COPY ["src/Api/", "/app/src/Api/"]
COPY ["src/Domain/", "/app/src/Domain/"]
COPY ["src/Common/", "/app/src/Common/"]
COPY ["src/Infrastructure/", "/app/src/Infrastructure/"]
COPY ["src/Application/", "/app/src/Application/"]

WORKDIR /app/src/Api
RUN dotnet publish "Api.csproj" -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080

COPY --from=build /app/src/Api/out .

ENTRYPOINT ["dotnet", "Api.dll"]


